travis:
  secure:
    BINSTAR_TOKEN: uJ3B6i7J+yRVfwzpN+R7S/DauE6BtJsVZdHNe+PX3Ja5zM1j7aLAFIY9oIYbTngKutBxcmC+gatO0anIpwX1iE04NFyIC/S+oTSRywvj6kBd9zJPMFtw6clVGFCxytBIL5Xjb4Eu+jP//Jrto45tvmNjebpmtlUVJH1TBwB0JD3BpnSA4PZ7ySwHNCxaGvIwEB9H8uw+q5yYZGppuJ2I93lWp80HVhW/JMsqAv77Q2PVlcUwzXTetKxfxbmEHixVcHBcdHntQ2rzrklP+ZLpc8UmiU0heqzqecmhMnnKSn9s1HUbb+LGMh2qhQc9+I5z/ID8oBtLwGDcJ7WVn8DaJsa0AcExhAHFxYSZQG5ihtJbg3/zF3Abhx/8FwHdqx8p9+4ql0idY9n9hNKvXrp3PkxVufrJtyOlHjTa0/4QkxZKtL5MFgeKIrWxNpUzzPlwAkkQhCcU9hcP4F5E2bxx5ZQOhvFAsQCUSeT13n4VrXgM5sdALaXHO1CCfrFkNvUGcvNn2MAFvxeFQob9As1lFrfWujg2ccJs4YLwMIdzGtzKaplzqUEf9A0ciuTgOwHJoxDISKRqz2J9x2HA0zLDVBzzQcCdGzmeKy1D5PtKEQd9A2ntYWD0wh7c4ZZ5d9RvbZlVZ2c65YMQGzBfeIY/8KD8NBohQXwtHPGeLjvdMDM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
